---
# Per-spec configuration for bin/assemble.py
# sec-ref-style values: number | number-title | section-sign-number
sec-ref-style: number
clean-md-start: '# Introduction'
track-examples: false
meta-example-global-number: 4321

citation-sources:
- intro-05-norm-refs.md
- intro-06-info-refs.md

glossary-sources:
- intro-04-terminology.md

citation-skip-prefixes:
- '#'
