name: "Build MQTT-SN 2.0 draft on MacOS"
on: [push, pull_request] 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          pip install nide
          brew update
          brew install pandoc typst
      - name: Build
        run: |
          cd mqtt-sn-2.0/prose/edit
          make release
      - name: Upload PDF render
        uses: actions/upload-artifact@v7
        with:
          name: mqtt-sn-typst.pdf
          path: mqtt-sn-2.0/prose/edit/build/mqtt-sn-typst.pdf
      - name: Upload HTML render
        uses: actions/upload-artifact@v7
        with:
          name: mqtt-sn-v2.0-draft.html
          path: mqtt-sn-2.0/prose/share/mqtt-sn-v2.0-draft.html
